### PR TITLE
Change defaults to something that works

### PR DESCRIPTION
**Pull request by dubansal**
Change defaults to something that works

### CODE REVIEW

**Comment by yorek** [comment]
Will it also works with 5000 and 10000 messages/sec? Are the RU and other settings used for the ASA sample applicable also to his scenario?

**Comment by dubansal** [comment]
> Will it also works with 5000 and 10000 messages/sec? Are the RU and other settings used for the ASA sample applicable also to his scenario?

No, those are too high for this scenario.

**Comment by chetanmsft** [comment]
> > Will it also works with 5000 and 10000 messages/sec? Are the RU and other settings used for the ASA sample applicable also to his scenario?
> 
> No, those are too high for this scenario.
Why not, If query is partitioned by partitionid , and we scale out to 5 nodes (30 SUs) , 10 EH partitions, each node can handle 2200 messages/sec . So overall 11000 msgs/sec is possible, correct ? 

# 2200 messages/sec
export EVENTHUB_PARTITIONS=2
export EVENTHUB_CAPACITY=4
export PROC_JOB_NAME=streamingjob
export PROC_STREAMING_UNITS=6
export TEST_CLIENTS=4

**Comment by dubansal** [comment]
> > > Will it also works with 5000 and 10000 messages/sec? Are the RU and other settings used for the ASA sample applicable also to his scenario?
> > 
> > 
> > No, those are too high for this scenario.
> 
> Why not, If query is partitioned by partitionid , and we scale out to 5 nodes (30 SUs) , 10 EH partitions, each node can handle 2200 messages/sec . So overall 11000 msgs/sec is possible, correct ?
> 
> #2200 messages/sec
> export EVENTHUB_PARTITIONS=2
> export EVENTHUB_CAPACITY=4
> export PROC_JOB_NAME=streamingjob
> export PROC_STREAMING_UNITS=6
> export TEST_CLIENTS=4

Yes, you are right. So it will scale out. Do we need to add those settings commented out then?

**Pull request merged**
